### ISSUE TITLE
Issue marking a day

### ISSUE THREAD

**Issue by Purdual10** [marcohc/RobotoCalendarView#5]
Hi, Thank you for share your code, is amazing. I have a question, if I want to mark a day in a concret month I have do like this:

if(currentMonthIndex==3){
			final Calendar calendar = Calendar.getInstance(Locale.getDefault());
			calendar.add(calendar.DAY_OF_MONTH, 28);
			robotoCalendarView.markDayWithStyle(RobotoCalendarView.GREEN_CIRCLE, calendar.getTime());
			robotoCalendarView.markDayAsCurrentDay(calendar.getTime());
}

But if I do this and I execute the marked day of march is 18 and not 28. Thanks

**Comment by Purdual10** [comment]
How to robotoCalendarView.markDayAsSelectedDay(); multiple dates in your calendar? thanks

**Comment by marcohc** [comment]
Hi Purdual10, sorry about the response delay.

First, you're adding days to the current calendar, not selecting the 28th of the current month:
```java
calendar.add(calendar.DAY_OF_MONTH, 28);
```
Second, 
```java
robotoCalendarView.markDayAsSelectedDay();
```
it's just to mark the current day, not multiple dates.
