### ISSUE TITLE
Change the calendar to start on a Monday

### ISSUE THREAD

**Issue by jackjamieson** [marcohc/RobotoCalendarView#6]
I can change the days of the week to start on Monday but the numbers of the days do not change with it.  I tried changing locales around but that doesn't seem to have any effect except changing the language.

Is it possible to do this?

**Comment by marcohc** [comment]
Hi, please check again, it changes.

**Comment by jatindersi** [comment]
i am getting the same error Weekday getting changed but calendar is remaining same no shuffle in date

**Comment by bhupalreddykokkanti** [comment]
Even I am also facing same issue. I changed the locale to UK English then by default I am getting monday as the first day of the week. Can you please let me know how to make it flexible without depending on the locale in the device
